### ISSUE TITLE
VSCode SFTP settings incorrectly changed port number

### ISSUE THREAD

**Issue by sm11963** [NevinAF/bga-ts-template#11]
~The SFTP port in my existing sftp.json file was changed from 2022 to 22 when I ran the init today.~

The default should be 2022 (recently updated by BGA) ~and also the init script probably shouldn't change the port if it exists.~

---

Okay, not as simple as I thought. Here is what happened:
1. I use split SFTP settings, see here: https://en.doc.boardgamearena.com/Setting_up_BGA_Development_environment_using_VSCode#Split_settings_for_version_control
2. My SFTP port, host, protocol, auth etc is defined globally, not as part of the project.
3. The initialize script added in port, protocol, host, etc - overriding my remote settings (and because the port is outdated, it broke my SFTP).

SO the fix for this might not be very simple. Maybe we could branch logic if the "remote" key is found in the existing SFTP settings. 

But what would definitely improve the situation at bare minimum is to update the port number to the latest default. I can put up a pull request for that at minimum.

**Comment by sm11963** [comment]
Updated the issue to reflect the real underlying issue that happened.

**Comment by NevinAF** [comment]
Thank you for making that fix!
