### ISSUE TITLE
dojo.setStyle requiring full computed style

### ISSUE THREAD

**Issue by sm11963** [NevinAF/bga-ts-template#13]
Example code
```
dojo.setStyle("thedeckcard", {
	'backgroundImage': `url("${g_gamethemeurl}/img/mock_card.jpg")`,
	'backgroundSize': '134px 182px',
	'width': '134px',
	'height': '182px',
});
```

Results in the error:
```
Argument of type '{ backgroundImage: string; backgroundSize: string; width: string; height: string; }' is not assignable to parameter of type 'string | DomComputedStyle'.
  Type '{ backgroundImage: string; backgroundSize: string; width: string; height: string; }' is missing the following properties from type 'DomComputedStyle': accentColor, alignContent, alignItems, alignSelf, and 496 more.ts(2345)
```
In context:
<img width="1223" alt="Screenshot 2024-09-15 at 8 02 56 PM" src="https://github.com/user-attachments/assets/8ed4fafe-6f8b-43cc-a372-af42825dd1b3">

Looks like the type just needs to be made into a partial (`Partial<DomComputedStyle>`). That works for me, PR coming up.

**Comment by NevinAF** [comment]
Thanks for pointing out! I will go ahead and merge your fix for now.

I'm currently working on a massive update which essentially converts all Dojo and BGA source code to Typescript. This allows developers to inspect functions for what they are specifically doing. The conversion has also revealed some of the typing issues (like the one provided), even from the official docs/code.
