### ISSUE TITLE
The TS build is broken on the last release

### ISSUE THREAD

**Issue by thoun** [NevinAF/bga-ts-template#19]
Running the following command on Refuge BGA project :
`npx tsc -p source/client --outFile refuge.js`

Ends up with

error TS2688: Cannot find type definition file for 'bga-ts-template'.
  The file is in the program because:
    Entry point of type library 'bga-ts-template' specified in compilerOptions

  source/client/tsconfig.json:64:14
    64   "types": [ "bga-ts-template" ], // Includes all non-module types which are on HTML script tags.
                    ~~~~~~~~~~~~~~~~~
    File is entry point of type library specified here.


Found 1 error.

**Comment by NevinAF** [comment]
The issue has been resolved with V2.0.6.
The package types property was carelessly deleted when pushing changes.
