### ISSUE TITLE
Bad file

### ISSUE THREAD

**Issue by fruiko** [NevinAF/bga-ts-template#2]
https://github.com/NevinAF/bga-ts-template/blame/996f219a722231ebfb87b781ce374fdcc3c36532/docs/tutorials/reversi.md#L381C2-L381C78

I think it should be yourgamename.game.php instead yourgamename.action.php

**Comment by NevinAF** [comment]
Thanks for pointing that out. Several spots referred to `yourgamename.action.php` that were supposed to state `yourgamename.game.php`.
