### ISSUE TITLE
Invalid GameState type 'private' on Build

### ISSUE THREAD

**Issue by cjhaviland** [NevinAF/bga-ts-template#3]
It seems when checking over GameState types during build of the JSONC file, if there is a private type it is not caught and instead treated as an invalid type. Should be thrown in with multipleactiveplayer and activeplayer condition.

https://github.com/NevinAF/bga-ts-template/blob/388c505ff26b105a5f734b06b085aa5d2a3fc1b6/init/build.js#L266

**Comment by NevinAF** [comment]
Thanks for reporting that oversight. Private state types are now handled on that line and no longer throw an error. I haven't developed a game that needed private states, so let me know if you are still seeing issues.

**Comment by cjhaviland** [comment]
The game I am currently playing around with is using a combination of server and client private states. I have a feeling using the JSONC file is going to give me trouble since I am not going to put the client side private states into GameStates, but it's going to throw an error in the TS file.

I am also blowing up your Discord haha,
