### ISSUE TITLE
Bad comparison check when comparing possible actions

### ISSUE THREAD

**Issue by cjhaviland** [NevinAF/bga-ts-template#5]
When iterating through Possible Actions and checking that the values are the same if an action is shared, the comparison fails even when the values are similar. Since we're comparing non-primitive values the comparison is by reference so it will always return falsy.

https://github.com/NevinAF/bga-ts-template/blob/388c505ff26b105a5f734b06b085aa5d2a3fc1b6/init/build.js#L338

Possible Solutions:
-  Compare the objects by JSON string: `JSON.stringify(possibleActions.get(action)) === JSON.stringify(actions[action])`
   - This would require the key value pairs to be in the same order, which may be for the best.
- Using LoDash `_.isEqual()` 
   - Then you're relying on a third party library.
- A custom compare function that iterates through keys and compares values and types

**Comment by NevinAF** [comment]
Thanks for reporting! There are many things like that that I was thinking about when coding but never ended up creating a test case for. Your solutions are wonderful and I opted for the third option for completeness.

 This will still throw an error if you use a non-value type for `typescriptType`, but this is an advanced case as JSON 
 params on actions need custom PHP for parsing. There are still some things I am considering about generating the action PHP file, and there are workarounds to this issue from a typescript standpoint.
