### ISSUE TITLE
TypeError: initialprivate is not iterable

### ISSUE THREAD

**Issue by cjhaviland** [NevinAF/bga-ts-template#6]
When checking the initialprivate state set on a multipleactiveplayer state, it is trying to iterate when the result is actually an integer.

https://github.com/NevinAF/bga-ts-template/blob/388c505ff26b105a5f734b06b085aa5d2a3fc1b6/init/build.js#L439

Since the JSONC schema requires initialprivate to be of type integer, then this check shouldn't be iterating over anything. Just checking that the set key points to a valid private state.

**Comment by NevinAF** [comment]
Thanks for reporting that oversight. This for loop has been removed and the error logs have been updated accordingly. I haven't developed a game that needed private states, so let me know if you are still seeing issues.
