### ISSUE TITLE
ajaxcall is deprecated for bgaPerformAction

### ISSUE THREAD

**Issue by cjhaviland** [NevinAF/bga-ts-template#8]
Add new way of checking action and performing an ajax call to the base game class.

https://en.doc.boardgamearena.com/Game_interface_logic:_yourgamename.js#Actions

**Comment by NevinAF** [comment]
Sorry for the delay, I'm currently working on a massive update which essentially converts all Dojo and BGA source code to Typescript which will include this change

**Comment by NevinAF** [comment]
The BGA-TS-Template has been upgraded to a new major release. This contains better type-checking, full source code in TS, and safer class types (can't use nonexistent class definitions). As a result, the `bgaPerformAction` function and many other missing members have been added to all source code types.
